# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orglist_company_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglist',
            name='company_state',
            field=models.CharField(choices=[('AndhraPradesh', 'AndhraPradesh'), ('Tamilnadu ', 'Tamilnadu'), ('Maharastra', 'Maharastra'), ('Karnataka', 'Karnataka'), ('Telangana', 'Telangana')], default='AndhraPradesh', max_length=40),
        ),
    ]
